# Generated by Django 3.0.2 on 2020-02-01 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('equity', models.FloatField()),
                ('cash', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=4)),
                ('qty', models.IntegerField()),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_executed', models.DateTimeField()),
                ('order_type', models.CharField(choices=[('MRKT', 'Market'), ('LMT', 'Limit'), ('STOP', 'Stop'), ('STLS', 'Stop Loss')], max_length=4)),
                ('side', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=4)),
                ('time_in_force', models.CharField(choices=[('DAY', 'Day'), ('DAYX', 'Day+Extended Hours'), ('GTC', 'Good Til Canceled'), ('FOK', 'Fill or Kill'), ('IOC', 'Immediate or Cancel'), ('OPG', 'At-the-Open'), ('CLS', 'At-the-Close')], max_length=4)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='website.Position')),
            ],
        ),
    ]
